### ISSUE TITLE
代码错误

### ISSUE THREAD

**Issue by Udacitymiaomiao** [udacity/wmpnd-issues-cn#12]
## 教室地址
6-4

## 截图
![wechatimg62](https://user-images.githubusercontent.com/33112888/39295892-23dd1076-4972-11e8-819b-eaa8a789aecd.jpeg)

## 具体描述
代码写错了，视频里是对的，底下的写错了

**Comment by sylviasun916** [comment]
@evestorm  这个不归我管哦 我不负责课程开发里的代码修正哦

**Comment by wctjerry** [comment]
谢谢反馈，我把这个修了。
