### ISSUE TITLE
文本概念性错误

### ISSUE THREAD

**Issue by WillBeethoven** [udacity/wmpnd-issues-cn#2]
## 截图
![screen shot 2018-04-08 at 22 09 49](https://user-images.githubusercontent.com/14329786/38468500-9294b5ca-3b79-11e8-8ec1-d7ec760de87d.png)

## 具体描述
1. 元素是 element，通常代指 HTML 标签，正确说法是属性--attribute。
2. `<title>` 是一个 HTML 元素。
3. 缺少元素 `<img>` 的声明。

正确表述：有关元素 `<img>` 的属性 `alt` 和 `title` 的异同，下列正确的说法是：

**Comment by evestorm** [comment]
@WillBeethoven 👍
