### ISSUE TITLE
建议项目使用英文路径

### ISSUE THREAD

**Issue by georgefeng** [udacity/wmpnd-issues-cn#23]
## 课程导航+地址
小程序（二）> 开启小程序开发之旅 > 9.创建项目

## 截图
![image](https://user-images.githubusercontent.com/23147020/39742835-9015412e-52d1-11e8-8659-c8834b802db6.png)

## 具体描述
视频34秒创建新文件夹存放项目，用的是中文`商城`作为文件夹名，中文路径可能会导致一些代码异常，建议使用英文路径。

**Comment by wctjerry** [comment]
@georgefeng 小程序环境下好像还好，或者能否举一个例字？

**Comment by georgefeng** [comment]
@wctjerry 完成课程应该是没有问题的。其他的话，比方说在windows上开发，然后部署到linux的服务器上，中文文件夹可能会报错。

**Comment by wctjerry** [comment]
@georgefeng 嗯，有道理。我看一下怎么给学生备注。谢谢反馈！
