### ISSUE TITLE
视频有杂音

### ISSUE THREAD

**Issue by TUPOBO** [udacity/wmpnd-issues-cn#25]
## 课程导航+地址
小程序（二）> 搭建商城首页 > 5. Web API 实现综述

## 截图

![image](https://user-images.githubusercontent.com/19498922/39749466-56aea20e-52e5-11e8-81f2-b76afab2fa6d.png)

## 具体描述
该单元的第二个视频有明显杂音

**Comment by lolipopshock** [comment]
已经上传新的视频。
