### ISSUE TITLE
2-8幻灯片笔误

### ISSUE THREAD

**Issue by georgefeng** [udacity/wmpnd-issues-cn#29]
## 课程导航+地址
微信小程序（二） > 搭建商城首页 > [8.在服务端实现下载商品数据的 API](https://classroom.udacity.com/nanodegrees/nd666-cn-2/parts/0f0857b1-ca85-4ae2-8877-f132f1aa3e5f/modules/281eaa06-6135-4227-8c9b-e3ed64eb8ed8/lessons/cd261f5d-1938-44e5-b125-0bd0464c02f6/concepts/c233860f-5283-424a-ab68-488934b93a5d)

## 截图
![image](https://user-images.githubusercontent.com/23147020/39757012-0aa60190-52fe-11e8-8492-ee10646d192f.png)

## 具体描述
视频23s处 路路由  -> 路由

**Comment by lolipopshock** [comment]
已经改正并重新上传。
