### ISSUE TITLE
视频无法播放

### ISSUE THREAD

**Issue by ChrisMaslow** [udacity/wmpnd-issues-cn#36]
## 课程导航+地址
例子：搭建商城首页 >  [5.Web API 实现综述](https://classroom.udacity.com/nanodegrees/nd666-cn-2/parts/0f0857b1-ca85-4ae2-8877-f132f1aa3e5f/modules/281eaa06-6135-4227-8c9b-e3ed64eb8ed8/lessons/cd261f5d-1938-44e5-b125-0bd0464c02f6/concepts/72a4cff7-acd2-4a04-8df5-bbed8482647c)

## 截图
![2018-05-10 12 43 13](https://user-images.githubusercontent.com/28378317/39852609-0246349a-5450-11e8-9dcc-725043fb2cd4.png)

## 具体描述
该页第二段视频在YouTube无法播放。

**Comment by wctjerry** [comment]
已修复，你再试试 @ChrisMaslow
