### ISSUE TITLE
cn-wechat-weather 无 2-6 分支

### ISSUE THREAD

**Issue by WillBeethoven** [udacity/wmpnd-issues-cn#4]
## [教室
地址](https://classroom.udacity.com/nanodegrees/nd666-cn-1/parts/0df2bc48-b519-43b3-94af-9e2fad59c3d2/modules/b30b76c5-6a21-4e31-8d1e-62a21ec8a8f4/lessons/3690bd9a-1c54-4940-861d-f93ad1491c5a/concepts/87e8a98e-72c1-4f91-89a6-affcb43feaf5)

## 截图

![screen shot 2018-04-09 at 12 11 12](https://user-images.githubusercontent.com/14329786/38479022-3433b8fc-3bef-11e8-84c3-05f4162adec2.png)

## 具体描述
视频演示的是 `2-6` 实际分支只有 `2-5`。

**Comment by evestorm** [comment]
done
