### ISSUE TITLE
课程二第四小节的home.wxss代码中缺少.bg的样式

### ISSUE THREAD

**Issue by vclub** [udacity/wmpnd-issues-cn#40]
## 课程导航+地址
课程2 > 搭建商城首页 > 4.前端页面设计

## 截图
<img width="1201" alt="screen shot 2018-05-12 at 10 38 36 pm" src="https://user-images.githubusercontent.com/3147593/39958451-9b872c86-5635-11e8-87b3-c6eb26e293e3.png">

## 具体描述
我使用线上代码显示的效果有问题
<img width="497" alt="screen shot 2018-05-12 at 10 41 50 pm" src="https://user-images.githubusercontent.com/3147593/39958459-bef55d82-5635-11e8-8bf4-40f5a9d05307.png">
我添加一个.bg的样式才能达到视频中显示的样子

**Comment by wctjerry** [comment]
@vclub 谢谢反馈，这个其实是一个可选项，我在第一课结束的地方加上了，有兴趣的话可以点击链接查看代码。
![image](https://user-images.githubusercontent.com/13818844/39979808-2e358596-577b-11e8-9f04-05d43dfbf835.png)
