### ISSUE TITLE
视频无法播放

### ISSUE THREAD

**Issue by evestorm** [udacity/wmpnd-issues-cn#50]
## 课程导航+地址
[搭建商城首页](https://classroom.udacity.com/nanodegrees/nd666-cn-1/parts/b0292bd2-7b16-40ec-a16e-928e01e414c6/modules/77ced544-ce41-4fd1-a6da-8981047785ed/lessons/cd261f5d-1938-44e5-b125-0bd0464c02f6/concepts/b0aa4349-df3c-4e0e-bf59-5cd4269d6b7d)

## 截图
![image](https://user-images.githubusercontent.com/18142851/40339848-d0949e88-5dae-11e8-98cd-6105e8e98cbc.png)

## 具体描述
该视频在youtobe上无法播放

**Comment by wctjerry** [comment]
done!
