### ISSUE TITLE
课程外链打开失败

### ISSUE THREAD

**Issue by DonaldDai** [udacity/wmpnd-issues-cn#53]
## 课程导航+地址
开启小程序开发之旅

## 截图
![image](https://user-images.githubusercontent.com/14327519/40414551-18349872-5eab-11e8-8927-7fdecaf47206.png)
![image](https://user-images.githubusercontent.com/14327519/40414587-38a5da1c-5eab-11e8-9b5e-275372ef0269.png)

## 具体描述
不加参数的这个[外链](https://s3.cn-north-1.amazonaws.com.cn/u-img/%E5%95%86%E5%9F%8E%E5%B0%8F%E7%A8%8B%E5%BA%8F%E4%BA%A4%E4%BA%92%E6%A6%82%E8%A7%88.png)可以正常打开

**Comment by wctjerry** [comment]
@DonaldDai 我重新上传了一下，你再试试看。
