### ISSUE TITLE
素材链接未给出

### ISSUE THREAD

**Issue by DonaldDai** [udacity/wmpnd-issues-cn#54]
## 课程导航+地址
1-10

## 截图
![image](https://user-images.githubusercontent.com/14327519/40418607-68b22990-5eb5-11e8-97a1-bdc6195af3da.png)

![image](https://user-images.githubusercontent.com/14327519/40418770-d1d2ccae-5eb5-11e8-8701-cd7131c0f0fb.png)

## 具体描述
课程1中用到了图标素材，可以通过 `git checkout 1-2` 的方式获取素材，但是像 **课程2-前端页面设计** 中使用到图标素材的时候给出了下载链接那样做体验会更好，也更符合视频的逻辑

**Comment by wctjerry** [comment]
@DonaldDai 第一课里面有这个链接，你看看能不能下载。

**Comment by DonaldDai** [comment]
可以下载，看走眼了😂
为什么我们的课章节不一样呢？我的只有11节
另外这个页面上的 tabBar 的格式看起来出了问题

**Comment by wctjerry** [comment]
@DonaldDai 哈哈 忽略，我看的是老版本，以你的为准。 tabBar 我也修复一下。
