### ISSUE TITLE
页面体验优化建议

### ISSUE THREAD

**Issue by DonaldDai** [udacity/wmpnd-issues-cn#56]
## 课程导航+地址
2-4

## 截图
![image](https://user-images.githubusercontent.com/14327519/40419058-aac07782-5eb6-11e8-8f2d-e6528dc14580.png)

## 具体描述
页面中有多个外链的时候，如果外链的文字描述更语义化会更方便学员查找，比如 [官方文档-初始化数据](https://websiteholder.com)

**Comment by wctjerry** [comment]
谢谢反馈，我们会注意这个问题，感谢！

**Comment by DonaldDai** [comment]
Thanks♪(･ω･)ﾉ
