### ISSUE TITLE
链接两旁空格不一致

### ISSUE THREAD

**Issue by DonaldDai** [udacity/wmpnd-issues-cn#57]
## 课程导航+地址
2-4

## 截图
![image](https://user-images.githubusercontent.com/14327519/40419269-5c483ce2-5eb7-11e8-9233-8ff12bc82091.png)

## 具体描述
如图，左边无空格，右边有空格

**Comment by wctjerry** [comment]
谢谢反馈，已修改。

**Comment by DonaldDai** [comment]
已确认修复
