### ISSUE TITLE
此处使用顿号和第二行格式一致或许更合适

### ISSUE THREAD

**Issue by DonaldDai** [udacity/wmpnd-issues-cn#58]
## 课程导航+地址
2-6

## 截图
![image](https://user-images.githubusercontent.com/14327519/40419702-bafa2a9c-5eb8-11e8-8b46-234604dbb113.png)

## 具体描述
如题图

**Comment by wctjerry** [comment]
已修改，谢谢反馈！

**Comment by DonaldDai** [comment]
已确认修复
