### ISSUE TITLE
外链打开失败

### ISSUE THREAD

**Issue by DonaldDai** [udacity/wmpnd-issues-cn#59]
## 课程导航+地址
2-7

## 截图
![image](https://user-images.githubusercontent.com/14327519/40419880-2d410878-5eb9-11e8-8c9d-33de519a0588.png)

![image](https://user-images.githubusercontent.com/14327519/40419886-321b6528-5eb9-11e8-8f58-02b39ed67344.png)

## 具体描述
[此链接](https://s3.cn-north-1.amazonaws.com.cn/cn-static.udacity.com/nd666/images%26sql.zip)可下载对应文件

**Comment by wctjerry** [comment]
@DonaldDai 应该可以了，再试一下~

**Comment by DonaldDai** [comment]
已确认修复
