### ISSUE TITLE
点击图片为大图后无法显示全部

### ISSUE THREAD

**Issue by evestorm** [udacity/wmpnd-issues-cn#61]
## 开启小程序之旅——>阅读交互图
[阅读交互图](https://classroom.udacity.com/nanodegrees/nd666-cn-2/parts/0f0857b1-ca85-4ae2-8877-f132f1aa3e5f/modules/281eaa06-6135-4227-8c9b-e3ed64eb8ed8/lessons/d00b0069-91c0-434e-b4e5-42b660b4eba8/concepts/a6116378-e0b4-4334-bd78-cc3e990f817b)

## 截图

![image](https://user-images.githubusercontent.com/18142851/40432392-2e91c5fa-5edc-11e8-9f58-0c7334d4dbec.png)

![image](https://user-images.githubusercontent.com/18142851/40432268-df108084-5edb-11e8-9ce9-33a35df9c3c6.png)

## 具体描述
点击第一张图后会展示大图，但无论怎样滚动都看不到图片的上半部分

**Comment by wctjerry** [comment]
@evestorm 这张图在课程中有下载链接，建议下载看。
