### ISSUE TITLE
无字幕+视频中文字错误

### ISSUE THREAD

**Issue by evestorm** [udacity/wmpnd-issues-cn#62]
## 搭建商城首页
[小程序开发流程的介绍](https://classroom.udacity.com/nanodegrees/nd666-cn-2/parts/0f0857b1-ca85-4ae2-8877-f132f1aa3e5f/modules/281eaa06-6135-4227-8c9b-e3ed64eb8ed8/lessons/cd261f5d-1938-44e5-b125-0bd0464c02f6/concepts/b0aa4349-df3c-4e0e-bf59-5cd4269d6b7d?contentVersion=1.0.0&contentLocale=zh-cn)

## 截图

> 无字幕

![image](https://user-images.githubusercontent.com/18142851/40433209-06a2d14a-5ede-11e8-985d-bbea07a2a7e5.png)

> 界面面，多了个面字

![image](https://user-images.githubusercontent.com/18142851/40433155-eaadefb0-5edd-11e8-8c58-cb75660d1709.png)

**Comment by wctjerry** [comment]
@evestorm 已经修复了，谢谢反馈！
