### ISSUE TITLE
外链与链接文本不符

### ISSUE THREAD

**Issue by evestorm** [udacity/wmpnd-issues-cn#63]
## 搭建商品首页
[Web API 实现综述](https://classroom.udacity.com/nanodegrees/nd666-cn-2/parts/0f0857b1-ca85-4ae2-8877-f132f1aa3e5f/modules/281eaa06-6135-4227-8c9b-e3ed64eb8ed8/lessons/cd261f5d-1938-44e5-b125-0bd0464c02f6/concepts/72a4cff7-acd2-4a04-8df5-bbed8482647c?contentVersion=1.0.0&contentLocale=zh-cn)

## 截图

![image](https://user-images.githubusercontent.com/18142851/40434355-c1d61bc8-5ee0-11e8-8ca0-ef0162d05dd5.png)

## 具体描述

维基百科链接打开后仍是MDN链接

**Comment by wctjerry** [comment]
@evestorm 好了，请看一下。
