### ISSUE TITLE
资源无法下载

### ISSUE THREAD

**Issue by evestorm** [udacity/wmpnd-issues-cn#64]
## 地址
[数据库介绍](https://classroom.udacity.com/nanodegrees/nd666-cn-2/parts/0f0857b1-ca85-4ae2-8877-f132f1aa3e5f/modules/281eaa06-6135-4227-8c9b-e3ed64eb8ed8/lessons/cd261f5d-1938-44e5-b125-0bd0464c02f6/concepts/e62e9659-231a-4fc2-981f-34320976557c?contentVersion=1.0.0&contentLocale=zh-cn)

## 截图
![image](https://user-images.githubusercontent.com/18142851/40435145-99400b40-5ee2-11e8-84e6-5c40ead93621.png)

## 具体描述
右键或直接点击无法下载文件

**Comment by wctjerry** [comment]
@evestorm 应该好了，试试~
