### ISSUE TITLE
占位文字未删除？

### ISSUE THREAD

**Issue by evestorm** [udacity/wmpnd-issues-cn#65]
## 搭建商品首页
 [实现商品详情的数据下载](https://classroom.udacity.com/nanodegrees/nd666-cn-2/parts/0f0857b1-ca85-4ae2-8877-f132f1aa3e5f/modules/281eaa06-6135-4227-8c9b-e3ed64eb8ed8/lessons/cd261f5d-1938-44e5-b125-0bd0464c02f6/concepts/31412af2-3cdf-43df-9da8-18fa7113d7d0?contentVersion=1.0.0&contentLocale=zh-cn)

## 截图
![image](https://user-images.githubusercontent.com/18142851/40459413-c86f954c-5f33-11e8-9afd-9d768a7b6d21.png)

## 具体描述

`[video] - L2 - 商品详情数据下载：服务端的实现` ，这一段话中是否有未删除的内容？比如 `[video] - L2`

**Comment by wctjerry** [comment]
done!
