### ISSUE TITLE
无字幕

### ISSUE THREAD

**Issue by evestorm** [udacity/wmpnd-issues-cn#66]
## 实现购物车页面
[修改购物车商品数量](https://classroom.udacity.com/nanodegrees/nd666-cn-2/parts/0f0857b1-ca85-4ae2-8877-f132f1aa3e5f/modules/281eaa06-6135-4227-8c9b-e3ed64eb8ed8/lessons/23c736f2-6e30-4ba9-b259-a933f9c9b15d/concepts/a4a0041e-ba22-49f6-af83-21f27c66ae9b?contentVersion=1.0.0&contentLocale=zh-cn)

## 截图
![image](https://user-images.githubusercontent.com/18142851/40460009-25e855e4-5f37-11e8-9c8f-d508013f6ba6.png)

## 具体描述
视频无字幕

**Comment by sylviasun916** [comment]
谢谢反馈 已修改字幕名 在部署中 稍后在教室内显示哦
