### ISSUE TITLE
无字幕

### ISSUE THREAD

**Issue by evestorm** [udacity/wmpnd-issues-cn#67]
## 添加评论功能
[评论功能概述](https://classroom.udacity.com/nanodegrees/nd666-cn-2/parts/0f0857b1-ca85-4ae2-8877-f132f1aa3e5f/modules/281eaa06-6135-4227-8c9b-e3ed64eb8ed8/lessons/ab25cea3-3ed1-4c19-80eb-f9aa326b1dfa/concepts/6319ace2-0c5f-42bd-ba7f-e9165261ba0d?contentVersion=1.0.0&contentLocale=zh-cn)

## 截图
![image](https://user-images.githubusercontent.com/18142851/40460082-9b1c3e70-5f37-11e8-955f-da6878500fcf.png)

## 具体描述
**两个视频**均没有字幕

**Comment by evestorm** [comment]
这一章节的总结部分，视频也没有字幕：
![image](https://user-images.githubusercontent.com/18142851/40460243-462f2ffc-5f38-11e8-88c5-82e3bc3f78a1.png)

**Comment by sylviasun916** [comment]
已修改字幕 在部署中 谢谢反馈！
