### ISSUE TITLE
3.4错别字

### ISSUE THREAD

**Issue by georgefeng** [udacity/wmpnd-issues-cn#68]
## 课程导航+地址
微信小程序开发（二） > [3.4 登陆功能的初步实现](https://classroom.udacity.com/nanodegrees/nd666-cn-2/parts/0f0857b1-ca85-4ae2-8877-f132f1aa3e5f/modules/281eaa06-6135-4227-8c9b-e3ed64eb8ed8/lessons/ff7a04f0-4142-43ee-8098-15a23dc08320/concepts/19b299a6-36ba-4f6e-a782-4723e20c8e06)

## 截图
![758l m245f9 9h_ 0t t92](https://user-images.githubusercontent.com/23147020/40473436-c4dc30bc-5f6e-11e8-864a-921b1e463aba.png)

## 具体描述
这辆 -> 这样

**Comment by wctjerry** [comment]
done
