### ISSUE TITLE
字幕缺失

### ISSUE THREAD

**Issue by LynnLululu** [udacity/wmpnd-issues-cn#7]
## 教室地址
https://classroom.udacity.com/nanodegrees/nd666-cn-1/parts/0df2bc48-b519-43b3-94af-9e2fad59c3d2/modules/b30b76c5-6a21-4e31-8d1e-62a21ec8a8f4/lessons/5b9ac545-0d41-4eba-b685-eb681ac0391b/concepts/8f361330-8ba4-406e-9fd8-addb5c22873a?contentVersion=1.0.0&contentLocale=zh-cn

## 截图
![image](https://user-images.githubusercontent.com/14273091/38852217-81af5b38-424b-11e8-98b3-c6e3b7113dfc.png)

## 具体描述
视频：https://s3.cn-north-1.amazonaws.com.cn/u-vid-hd/DxAF5oVsmAo.mp4
时间：00:23
少一句字幕：“那么，让我们来试一下吧”

**Comment by sylviasun916** [comment]
字幕格式错误 已修改 在部署中 非常感谢！
