### ISSUE TITLE
【字幕问题】5-2 练习：购物车页面的静态布局

### ISSUE THREAD

**Issue by PoBlue** [udacity/wmpnd-issues-cn#87]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd666-cn-2/parts/0f0857b1-ca85-4ae2-8877-f132f1aa3e5f/modules/281eaa06-6135-4227-8c9b-e3ed64eb8ed8/lessons/23c736f2-6e30-4ba9-b259-a933f9c9b15d/concepts/4b21bf0b-250a-4cd2-9932-189761d88760

## 截图
<img width="839" alt="2018-06-04 10 07 27" src="https://user-images.githubusercontent.com/9304701/40894968-7fb838b8-67df-11e8-8906-8bcd1735e38a.png">

## 具体描述
`视频` 应改为 `页面`

**Comment by sylviasun916** [comment]
已修改 谢谢反馈！ 在部署中 预计半小时后在教室内显示
