### ISSUE TITLE
课程视频无法播放

### ISSUE THREAD

**Issue by Udacitymiaomiao** [udacity/wmpnd-issues-cn#9]
## 教室地址
https://classroom.udacity.com/nanodegrees/nd666-cn-1/parts/0df2bc48-b519-43b3-94af-9e2fad59c3d2/modules/b30b76c5-6a21-4e31-8d1e-62a21ec8a8f4/lessons/ebfb8f5e-b4f8-4443-9239-2a6fd0cf596d/concepts/7bd0661a-5b7a-4415-8108-46e07b47e482

## 截图
<img width="1351" alt="2018-04-18 10 29 07" src="https://user-images.githubusercontent.com/33112888/38939501-a0f15a2c-435a-11e8-8b3d-e7f099cde30c.png">

## 具体描述
在墙外，此视频看不了

**Comment by evestorm** [comment]
fixed！

**Comment by Udacitymiaomiao** [comment]
赞！
